services:

  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - paperone

  postgresql:
    image: postgres:16-alpine
    shm_size: 10gb
    container_name: postgresql
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
    networks:
      - paperone

    volumes:
        - ./db_init:/docker-entrypoint-initdb.d/
        - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL","pg_isready -U ${DB_USER} -d ${DB_NAME}"]
        interval: 5s
        timeout: 5s
        retries: 20
        start_period: 30s

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: renderer
    restart: unless-stopped

    shm_size: 1gb

    environment:
      - AUTH_TOKEN=${secret-token}
      - CHROME_ARGS=--no-sandbox,--disable-dev-shm-usage,--disable-gpu

    ports:
      - "8081:8081"

    networks:
      - grafana

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_RENDERING_RENDERER_TOKEN=${secret-token}

      - GF_LOG_LEVEL=warning
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      - GF_SERVER_ROOT_URL=http://grafana:3000/
      - GF_SERVER_DOMAIN=grafana

      - GF_LOG_LEVEL=debug

    ports:
      - '3000:3000'
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/grafana/dashboards
      - grafana_storage:/var/lib/grafana
      - /shared:/shared
    command:
      - /bin/sh
      - -c
      - |
        /run.sh &
        sleep 15
        /create-token.sh
        wait

    networks:
      - grafana

  paperone:
    
    build:
      context: ./paperone
      dockerfile: Dockerfile
    
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgresql:5432/${DB_NAME}
      DB_HOST: postgresql
      DB_PORT: 5432

      YOUTRACK_TOKEN: ${YOUTRACK_TOKEN}
      YOUTRACK_URL: ${YOUTRACK_URL}

      GRAFANA_TOKEN: ${GRAFANA_TOKEN}

    networks:
      - paperone
      - grafana
    volumes:
      - ./dashboards:/app/dashboards
      - ./snapshots:/app/snapshots
      - ./logs:/app/logs
      - ./shared:/app/shared
    depends_on:
      postgresql:
        condition: service_healthy
      
volumes:
  postgres_data:
  redis_data:
  grafana_storage:

networks:
  paperone:
  grafana:
